const QUOTES_LIST = [
  { en: "Studying is not about time, it’s about effort.", vi: "Vấn đề của việc học không phải là thời gian, mà là sự nỗ lực.", author: "Anonymous" },
  { en: "To have another language is to possess a second soul.", vi: "Biết thêm về một ngôn ngữ khác cũng giống như có một linh hồn thứ hai.", author: "Charlemagne" },
  { en: "Once you stop learning, you start dying.", vi: "Khi bạn ngừng học, bạn bắt đầu chết dần đi.", author: "Albert Einstein" },
  { en: "The important thing is not to stop questioning. Curiosity has its own reason for existing.", vi: "Điều quan trọng là không ngừng đặt câu hỏi. Sự tò mò có lý do riêng để tồn tại.", author: "Albert Einstein" },
  { en: "An investment in knowledge pays the best interest.", vi: "Đầu tư vào kiến thức mang lại lợi nhuận cao nhất.", author: "Benjamin Franklin" },
  { en: "The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge.", vi: "Kẻ thù lớn nhất của kiến thức không phải là sự ngu ngốc, mà là ảo tưởng về sự hiểu biết.", author: "Stephen Hawking" },
  { en: "Real knowledge is to know the extent of one's ignorance.", vi: "Tri thức thực sự là biết rõ giới hạn sự thiếu hiểu biết của bản thân.", author: "Confucius" },
  { en: "Knowledge is power.", vi: "Kiến thức là sức mạnh.", author: "Francis Bacon" },
  { en: "Learning is not attained by chance, it must be sought for with ardor and attended to with diligence.", vi: "Sự học không đến ngẫu nhiên, nó phải được tìm kiếm bằng sự nhiệt huyết và chăm chỉ.", author: "Abigail Adams" },
  { en: "Procrastination makes easy things hard and hard things harder.", vi: "Sự trì hoãn khiến việc dễ trở nên khó và việc khó trở nên khó hơn.", author: "Mason Cooley" },
  { en: "Push yourself, because no one else is going to do it for you.", vi: "Hãy tự thúc đẩy bản thân, vì không ai làm điều đó thay bạn đâu.", author: "Anonymous" },
  { en: "Learning is a treasure that will follow its owner everywhere.", vi: "Học tập là một kho báu sẽ đi theo chủ nhân của nó đến bất cứ đâu.", author: "Chinese Proverb" },
  { en: "A little learning is a dangerous thing.", vi: "Học hành nửa vời là một điều nguy hiểm.", author: "Alexander Pope" },
  { en: "Education is not the learning of facts, but the training of the mind to think.", vi: "Giáo dục không phải là học thuộc các sự thật, mà là rèn luyện tâm trí cách suy nghĩ.", author: "Albert Einstein" },
  { en: "Wisdom is not a product of schooling but of the lifelong attempt to acquire it.", vi: "Sự khôn ngoan không phải là sản phẩm của trường học, mà là nỗ lực cả đời để đạt được.", author: "Albert Einstein" },
  { en: "Learning without thought is labor lost; thought without learning is perilous.", vi: "Học mà không suy nghĩ thì phí công; suy nghĩ mà không học thì nguy hiểm.", author: "Confucius" },
  { en: "The more I learn, the more I realize how much I don't know.", vi: "Càng học nhiều, tôi càng nhận ra mình biết ít đi.", author: "Albert Einstein" },
  { en: "Spoon feeding in the long run teaches us nothing but the shape of the spoon.", vi: "Thói quen nhồi nhét/mớm kiến thức lâu dài chỉ dạy chúng ta hình dáng của chiếc thìa chứ không dạy được gì khác.", author: "E.M. Forster" },
  { en: "To learn a language is to have one more window from which to look at the world.", vi: "Học một ngôn ngữ mới là mở thêm một cửa sổ để nhìn ra thế giới.", author: "Chinese Proverb" },
  { en: "Mistakes are proof that you are trying.", vi: "Sai lầm là bằng chứng cho thấy bạn đang nỗ lực.", author: "Anonymous" },
  { en: "Study hard, for the well is deep, and our brains are shallow.", vi: "Hãy học tập chăm chỉ, vì giếng kiến thức thì sâu mà não bộ chúng ta thì có hạn.", author: "Richard Baxter" },
  { en: "Never stop learning, because life never stops teaching.", vi: "Đừng bao giờ ngừng học hỏi, vì cuộc sống không bao giờ ngừng giảng dạy.", author: "Anonymous" },
  { en: "The beautiful thing about learning is nobody can take it away from you.", vi: "Vẻ đẹp của việc học là không ai có thể tước nó khỏi tay bạn.", author: "B.B. King" },
  { en: "Focus on being productive instead of busy.", vi: "Hãy tập trung vào việc tạo ra hiệu quả thay vì chỉ khiến bản thân bận rộn.", author: "Tim Ferriss" },
  { en: "Wake up with determination. Go to bed with satisfaction.", vi: "Thức dậy với sự quyết tâm. Đi ngủ với sự hài lòng.", author: "Anonymous" },
  { en: "Study now, be proud later.", vi: "Nỗ lực học tập hôm nay để tự hào vào ngày mai.", author: "Anonymous" },
  { en: "Focus on the process, and the results will follow.", vi: "Hãy tập trung vào quá trình học, kết quả tự khắc sẽ đến.", author: "Anonymous" },
  { en: "The expert in anything was once a beginner.", vi: "Chuyên gia nào cũng từng là kẻ nghiệp dư.", author: "Helen Hayes" },
  { en: "The limits of my language mean the limits of my world.", vi: "Giới hạn về ngôn ngữ là giới hạn về nhận thức, về thế giới.", author: "Ludwig Wittgenstein" },
  { en: "A different language is a different vision of life.", vi: "Một ngôn ngữ mới là một thế giới mới.", author: "Federico Fellini" },
  { en: "With language, you are at home anywhere.", vi: "Khi sử dụng được nhiều thứ tiếng, bạn cảm giác đi đâu cũng là nhà.", author: "Edward De Waal" },
  { en: "Knowledge of language is the doorway to wisdom.", vi: "Hiểu biết nhiều ngoại ngữ là cánh cửa dẫn đến tri thức.", author: "Roger Bacon" },
  { en: "Language is the blood of the soul into which thoughts run and out of which they grow.", vi: "Ngôn ngữ là nguồn sống của tâm hồn, là nguyên liệu cho tư duy và là sự thể hiện của tư duy phát triển.", author: "Oliver Wendell Holmes" },
  { en: "The journey of learning never truly ends.", vi: "Hành trình học tập thực sự không bao giờ kết thúc.", author: "Anonymous" },
  { en: "Learn from yesterday, live for today, hope for tomorrow.", vi: "Học từ ngày hôm qua, sống cho hôm nay và hy vọng vào ngày mai.", author: "Albert Einstein" },
  { en: "Learning is a journey, not a destination.", vi: "Học tập là một hành trình, không phải một đích đến.", author: "Anonymous" },
  { en: "Education is not preparation for life; education is life itself.", vi: "Giáo dục không phải sự chuẩn bị cho cuộc sống; giáo dục chính là cuộc sống.", author: "John Dewey" },
  { en: "Learning never exhausts the mind.", vi: "Học tập không bao giờ làm tâm trí cạn kiệt.", author: "Leonardo Da Vinci" },
  { en: "Study with purpose, not just pressure.", vi: "Hãy học với mục tiêu, không chỉ vì áp lực.", author: "Anonymous" },
  { en: "Consistency is the key to progress.", vi: "Sự kiên trì đều đặn là chìa khóa của tiến bộ.", author: "Anonymous" },
  { en: "A little progress each day adds up to big results.", vi: "Một chút tiến bộ mỗi ngày sẽ tạo nên kết quả lớn.", author: "Anonymous" },
  { en: "Focus on progress, not perfection.", vi: "Hãy tập trung vào tiến bộ, không phải sự hoàn hảo.", author: "Anonymous" },
  { en: "Study today, understand tomorrow.", vi: "Học hôm nay, hiểu biết ngày mai.", author: "Anonymous" },
  { en: "Don’t wish for success. Work for it.", vi: "Đừng chỉ ước thành công. Hãy nỗ lực vì nó.", author: "Anonymous" },
  { en: "Progress happens one step at a time.", vi: "Tiến bộ xảy ra từng bước một.", author: "Anonymous" },
  { en: "A focused mind can achieve great things.", vi: "Một tâm trí tập trung có thể đạt được những điều lớn lao.", author: "Anonymous" },
  { en: "Your effort is never wasted.", vi: "Nỗ lực của bạn không bao giờ là vô ích.", author: "Anonymous" },
  { en: "Believe you can, and you are halfway there.", vi: "Hãy tin rằng bạn có thể, và bạn đã đi được một nửa chặng đường.", author: "Theodore Roosevelt" },
  { en: "It always seems impossible until it’s done.", vi: "Mọi thứ dường như bất khả thi cho đến khi nó được hoàn thành.", author: "Nelson Mandela" },
  { en: "Keep going. You are closer than you think.", vi: "Hãy tiếp tục. Bạn đang gần mục tiêu hơn bạn nghĩ.", author: "Anonymous" },
  { en: "You can do hard things.", vi: "Bạn có thể làm được những điều khó khăn.", author: "Anonymous" },
  { en: "Your only limit is the one you set for yourself.", vi: "Giới hạn duy nhất là giới hạn bạn tự đặt ra cho mình.", author: "Anonymous" },
  { en: "Keep learning, keep growing, keep going.", vi: "Tiếp tục học, tiếp tục trưởng thành, tiếp tục tiến bước.", author: "Anonymous" },
  { en: "Turn challenges into opportunities to learn.", vi: "Biến thử thách thành cơ hội để học hỏi.", author: "Anonymous" },
  { en: "Be stronger than your excuses.", vi: "Hãy mạnh mẽ hơn những lời bào chữa của chính mình.", author: "Anonymous" },
  { en: "Don’t quit because it’s hard.", vi: "Đừng bỏ cuộc chỉ vì mọi thứ khó khăn.", author: "Anonymous" },
  { en: "Education is the most powerful weapon which you can use to change the world.", vi: "Giáo dục là vũ khí mạnh mẽ nhất mà bạn có thể dùng để thay đổi thế giới.", author: "Nelson Mandela" },
  { en: "Knowledge grows when it is shared.", vi: "Kiến thức phát triển khi được chia sẻ.", author: "Anonymous" },
  { en: "Education builds the foundation of a better future.", vi: "Giáo dục xây dựng nền móng cho một tương lai tốt đẹp hơn.", author: "Anonymous" },
  { en: "Learning is an investment in yourself.", vi: "Học tập là một khoản đầu tư vào chính mình.", author: "Anonymous" },
  { en: "Education helps you discover who you can become.", vi: "Giáo dục giúp bạn khám phá con người mà bạn có thể trở thành.", author: "Anonymous" },
  { en: "The more you understand, the more you can achieve.", vi: "Bạn càng hiểu biết, bạn càng có thể đạt được nhiều điều.", author: "Anonymous" },
  { en: "Education is the passport to the future.", vi: "Giáo dục là tấm hộ chiếu dẫn đến tương lai.", author: "Malcolm X" },
  { en: "Knowledge makes the unknown less frightening.", vi: "Kiến thức khiến những điều chưa biết trở nên bớt đáng sợ.", author: "Anonymous" },
  { en: "Education is a lifelong journey.", vi: "Giáo dục là một hành trình suốt đời.", author: "Anonymous" },
  { en: "Learn. Grow. Repeat.", vi: "Học hỏi. Trưởng thành. Lặp lại.", author: "Anonymous" },
  { en: "Read. Think. Grow.", vi: "Đọc. Suy nghĩ. Trưởng thành.", author: "Anonymous" },
  { en: "Don’t be afraid to make mistakes. Be afraid of not trying.", vi: "Đừng sợ mắc lỗi. Hãy sợ việc không thử.", author: "Anonymous" },
  { en: "Practice makes progress.", vi: "Luyện tập tạo nên sự tiến bộ.", author: "Anonymous" },
  { en: "Every new word is a new door.", vi: "Mỗi từ mới là một cánh cửa mới.", author: "Anonymous" },
  { en: "English is not a subject; it’s a skill.", vi: "Tiếng Anh không chỉ là một môn học; đó là một kỹ năng.", author: "Anonymous" },
  { en: "Learn a word today, use it tomorrow.", vi: "Học một từ hôm nay, sử dụng nó vào ngày mai.", author: "Anonymous" },
  { en: "Fluency comes from practice, not perfection.", vi: "Sự lưu loát đến từ luyện tập, không phải sự hoàn hảo.", author: "Anonymous" },
  { en: "Your English gets better every time you use it.", vi: "Tiếng Anh của bạn tốt hơn mỗi khi bạn sử dụng nó.", author: "Anonymous" },
  { en: "Don’t learn English just to pass a test. Learn it to express yourself.", vi: "Đừng học tiếng Anh chỉ để vượt qua một bài kiểm tra. Hãy học để thể hiện bản thân.", author: "Anonymous" },
  { en: "One sentence a day can change your English.", vi: "Một câu mỗi ngày có thể thay đổi khả năng tiếng Anh của bạn.", author: "Anonymous" },
  { en: "Keep going. Your future self will thank you.", vi: "Hãy tiếp tục. Chính bạn của tương lai sẽ cảm ơn bạn.", author: "Anonymous" },
  { en: "You don’t have to be great to start, but you have to start to be great.", vi: "Bạn không cần phải giỏi mới bắt đầu, nhưng bạn phải bắt đầu để trở nên giỏi.", author: "Zig Ziglar" },
  { en: "Success comes from never giving up.", vi: "Thành công đến từ việc không bao giờ bỏ cuộc.", author: "Anonymous" },
  { en: "Fall seven times, stand up eight.", vi: "Ngã bảy lần, đứng dậy tám lần.", author: "Japanese Proverb" },
  { en: "Don’t give up on a goal just because it takes time.", vi: "Đừng từ bỏ mục tiêu chỉ vì nó cần thời gian.", author: "Anonymous" },
  { en: "Every minute of practice brings you closer to your goal.", vi: "Mỗi phút luyện tập đưa bạn gần hơn tới mục tiêu.", author: "Anonymous" },
  { en: "The secret of success is consistency.", vi: "Bí quyết của thành công là sự kiên trì đều đặn.", author: "Anonymous" },
  { en: "Don’t compare your beginning to someone else’s middle.", vi: "Đừng so sánh khởi đầu của mình với chặng giữa của người khác.", author: "Tim Hiller" },
  { en: "The harder you work, the luckier you get.", vi: "Bạn càng chăm chỉ, bạn càng gặp nhiều “may mắn”.", author: "Gary Player" },
  { en: "You are capable of more than you think.", vi: "Bạn có khả năng làm được nhiều hơn bạn nghĩ.", author: "Anonymous" },
  { en: "Small progress is still progress.", vi: "Tiến bộ nhỏ vẫn là tiến bộ.", author: "Anonymous" },
  { en: "A little effort every day goes a long way.", vi: "Một chút nỗ lực mỗi ngày sẽ đưa bạn đi rất xa.", author: "Anonymous" },
  { en: "Learning another language is like becoming another person.", vi: "Học một ngôn ngữ mới là trở thành một con người mới.", author: "Haruki Murakami" },
  { en: "Work hard in silence, let success be your noise.", vi: "Nỗ lực làm việc trong im lặng, để thành công của bạn được lên tiếng.", author: "Frank Ocean" },
  { en: "There are no geniuses here, only those who try harder than you.", vi: "Ở đây không có thiên tài, chỉ có những người cố gắng hơn bạn.", author: "Anonymous" },
  { en: "Develop a passion for learning. If you do, you never cease to grow.", vi: "Hãy luôn đam mê học hỏi. Nếu làm được, bạn sẽ phát triển không ngừng.", author: "Anthony J. D'Angelo" }
];

const TIPS_LIST = [
  { category: "1. Confusing Words – Từ dễ nhầm", text: "Hai từ có nghĩa gần giống chưa chắc dùng giống nhau, hãy chú ý hoàn cảnh sử dụng." },
  { category: "1. Confusing Words – Từ dễ nhầm", text: "Đặt hai từ cạnh nhau và tìm điểm khác biệt thay vì học riêng từng từ." },
  { category: "1. Confusing Words – Từ dễ nhầm", text: "Đừng chỉ nhớ nghĩa tiếng Việt, hãy nhớ từ đó thường dùng trong trường hợp nào." },
  { category: "1. Confusing Words – Từ dễ nhầm", text: "Nếu hai từ đều có vẻ đúng, hãy xem từ nào thường xuất hiện trong câu tương tự." },
  { category: "1. Confusing Words – Từ dễ nhầm", text: "Khi hay nhầm hai từ, hãy học chúng cùng nhau để dễ phân biệt hơn." },
  { category: "1. Confusing Words – Từ dễ nhầm", text: "Hãy tự đặt một câu cho mỗi từ để thấy rõ sự khác nhau." },
  { category: "1. Confusing Words – Từ dễ nhầm", text: "Nếu hai từ chỉ khác nhau một chút về nghĩa, hãy tìm một ví dụ thật rõ cho từng từ." },
  { category: "1. Confusing Words – Từ dễ nhầm", text: "Đừng đoán từ chỉ dựa vào cách viết giống nhau." },
  { category: "1. Confusing Words – Từ dễ nhầm", text: "Khi gặp lại hai từ này, hãy dừng lại và tự phân biệt trước khi chọn." },
  { category: "1. Confusing Words – Từ dễ nhầm", text: "Nếu vẫn nhầm sau nhiều lần, hãy tạo một mẹo riêng để ghi nhớ chúng." },
  { category: "2. Synonyms – Từ đồng nghĩa", text: "Từ đồng nghĩa không phải lúc nào cũng thay thế được cho nhau." },
  { category: "2. Synonyms – Từ đồng nghĩa", text: "Hãy chú ý sắc thái của từng từ." },
  { category: "2. Synonyms – Từ đồng nghĩa", text: "Một số từ phù hợp với văn viết hơn giao tiếp." },
  { category: "2. Synonyms – Từ đồng nghĩa", text: "Đừng chọn từ khó hơn chỉ vì nghĩ nó “xịn” hơn." },
  { category: "2. Synonyms – Từ đồng nghĩa", text: "Nếu không chắc, hãy chọn từ bạn biết chắc là phù hợp." },
  { category: "2. Synonyms – Từ đồng nghĩa", text: "Hãy xem người bản ngữ thường dùng từ đó trong trường hợp nào." },
  { category: "2. Synonyms – Từ đồng nghĩa", text: "Đọc vài ví dụ sẽ giúp bạn cảm nhận sự khác nhau rõ hơn." },
  { category: "2. Synonyms – Từ đồng nghĩa", text: "Nếu hai từ đều có vẻ đúng, hãy kiểm tra xem từ nào tự nhiên hơn trong câu." },
  { category: "2. Synonyms – Từ đồng nghĩa", text: "Đừng cố học quá nhiều từ đồng nghĩa cùng lúc." },
  { category: "2. Synonyms – Từ đồng nghĩa", text: "Hãy học cách phân biệt trước khi cố ghi nhớ thêm từ mới." },
  { category: "3. Polysemy – Từ nhiều nghĩa", text: "Đừng cố học tất cả nghĩa của một từ cùng lúc." },
  { category: "3. Polysemy – Từ nhiều nghĩa", text: "Hãy bắt đầu với nghĩa bạn gặp thường xuyên nhất." },
  { category: "3. Polysemy – Từ nhiều nghĩa", text: "Mỗi nghĩa nên được ghi nhớ qua một câu cụ thể." },
  { category: "3. Polysemy – Từ nhiều nghĩa", text: "Gặp từ quen trong ngữ cảnh mới, đừng vội cho rằng nó có nghĩa cũ." },
  { category: "3. Polysemy – Từ nhiều nghĩa", text: "Hãy nhìn những từ xung quanh để đoán nghĩa phù hợp." },
  { category: "3. Polysemy – Từ nhiều nghĩa", text: "Nếu một nghĩa mới xuất hiện nhiều lần, hãy thêm nó vào danh sách cần học." },
  { category: "3. Polysemy – Từ nhiều nghĩa", text: "Đừng học một danh sách nghĩa dài mà không có ví dụ." },
  { category: "3. Polysemy – Từ nhiều nghĩa", text: "Hãy thử tự đoán nghĩa trước khi tra từ điển." },
  { category: "3. Polysemy – Từ nhiều nghĩa", text: "Khi đã nhớ nghĩa cơ bản, hãy từ từ học thêm những nghĩa khác." },
  { category: "3. Polysemy – Từ nhiều nghĩa", text: "Quan trọng nhất là hiểu đúng nghĩa của từ trong câu đang gặp." },
  { category: "4. Difficult Words – Từ khó nhớ", text: "Nếu cứ quên, hãy gắn từ với một hình ảnh hoặc tình huống quen thuộc." },
  { category: "4. Difficult Words – Từ khó nhớ", text: "Tự đặt một câu liên quan đến bản thân để từ dễ nhớ hơn." },
  { category: "4. Difficult Words – Từ khó nhớ", text: "Đừng cố học lại một từ quá nhiều lần trong một buổi." },
  { category: "4. Difficult Words – Từ khó nhớ", text: "Hãy quay lại với từ đó sau một vài ngày." },
  { category: "4. Difficult Words – Từ khó nhớ", text: "Nếu từ quá khó, hãy tìm cách giải thích đơn giản hơn." },
  { category: "4. Difficult Words – Từ khó nhớ", text: "Chia một từ dài thành những phần nhỏ nếu điều đó giúp bạn dễ nhớ." },
  { category: "4. Difficult Words – Từ khó nhớ", text: "Liên kết từ mới với một từ bạn đã biết." },
  { category: "4. Difficult Words – Từ khó nhớ", text: "Hãy thử sử dụng từ ngay sau khi học." },
  { category: "4. Difficult Words – Từ khó nhớ", text: "Viết một đoạn ngắn có chứa từ bạn đang khó nhớ." },
  { category: "4. Difficult Words – Từ khó nhớ", text: "Nếu vẫn quên, đừng nản, hãy thay đổi cách học thay vì chỉ học lại y hệt." },
  { category: "5. Application – Khi biết nghĩa nhưng không biết dùng", text: "Biết nghĩa chưa có nghĩa là bạn đã biết cách dùng từ." },
  { category: "5. Application – Khi biết nghĩa nhưng không biết dùng", text: "Hãy xem thêm vài câu ví dụ trước khi tự sử dụng." },
  { category: "5. Application – Khi biết nghĩa nhưng không biết dùng", text: "Thử đặt một câu mới thay vì copy câu mẫu." },
  { category: "5. Application – Khi biết nghĩa nhưng không biết dùng", text: "Hãy sử dụng từ trong một tình huống khác với ví dụ ban đầu." },
  { category: "5. Application – Khi biết nghĩa nhưng không biết dùng", text: "Nếu câu nghe không tự nhiên, hãy kiểm tra lại cách dùng của từ." },
  { category: "5. Application – Khi biết nghĩa nhưng không biết dùng", text: "Đừng chỉ học 'từ này nghĩa là gì', hãy học 'từ này dùng khi nào'." },
  { category: "5. Application – Khi biết nghĩa nhưng không biết dùng", text: "Nếu không chắc cách dùng, hãy tìm thêm những câu thực tế có từ đó." },
  { category: "5. Application – Khi biết nghĩa nhưng không biết dùng", text: "Một từ dùng đúng nhiều lần sẽ đáng nhớ hơn một từ chỉ học nghĩa." },
  { category: "5. Application – Khi biết nghĩa nhưng không biết dùng", text: "Hãy thử giải thích cách dùng của từ bằng chính lời của bạn." },
  { category: "5. Application – Khi biết nghĩa nhưng không biết dùng", text: "Nếu chỉ dùng được từ trong câu mẫu, bạn vẫn cần luyện thêm." },
  { category: "6. Collocations – Cụm từ hay đi cùng nhau", text: "Một số từ thường đi với nhau, hãy học cả cụm thay vì từng từ." },
  { category: "6. Collocations – Cụm từ hay đi cùng nhau", text: "Đừng dịch từng từ rồi ghép lại thành một cụm." },
  { category: "6. Collocations – Cụm từ hay đi cùng nhau", text: "Khi gặp một cụm xuất hiện nhiều lần, hãy ghi nhớ cả cụm." },
  { category: "6. Collocations – Cụm từ hay đi cùng nhau", text: "Hãy chú ý những từ thường đứng trước và sau từ mới." },
  { category: "6. Collocations – Cụm từ hay đi cùng nhau", text: "Nếu câu đúng nghĩa nhưng nghe không tự nhiên, hãy kiểm tra cách kết hợp từ." },
  { category: "6. Collocations – Cụm từ hay đi cùng nhau", text: "Học một vài cụm phổ biến sẽ hữu ích hơn học rất nhiều từ riêng lẻ." },
  { category: "6. Collocations – Cụm từ hay đi cùng nhau", text: "Khi học từ mới, hãy xem nó thường đi cùng những từ nào." },
  { category: "6. Collocations – Cụm từ hay đi cùng nhau", text: "Hãy tự đặt câu bằng cả cụm thay vì chỉ dùng một từ." },
  { category: "6. Collocations – Cụm từ hay đi cùng nhau", text: "Nếu không chắc một cụm có tự nhiên không, hãy kiểm tra ví dụ thực tế." },
  { category: "6. Collocations – Cụm từ hay đi cùng nhau", text: "Đừng cố tạo cụm mới chỉ bằng cách ghép những từ có nghĩa phù hợp." },
  { category: "7. Phrasal Verbs & Idioms", text: "Đừng cố đoán nghĩa của cả cụm bằng cách cộng nghĩa từng từ." },
  { category: "7. Phrasal Verbs & Idioms", text: "Hãy học phrasal verb như một cụm hoàn chỉnh." },
  { category: "7. Phrasal Verbs & Idioms", text: "Ghi nhớ cụm từ thông qua một câu cụ thể sẽ dễ hơn." },
  { category: "7. Phrasal Verbs & Idioms", text: "Nếu một cụm có nhiều nghĩa, hãy học từng nghĩa qua từng tình huống." },
  { category: "7. Phrasal Verbs & Idioms", text: "Đừng dịch idiom từng chữ sang tiếng Việt." },
  { category: "7. Phrasal Verbs & Idioms", text: "Hãy tìm một tình huống thực tế để ghi nhớ cụm từ." },
  { category: "7. Phrasal Verbs & Idioms", text: "Nếu một cụm quá hiếm, hãy ưu tiên hiểu khi gặp trước khi cố sử dụng." },
  { category: "7. Phrasal Verbs & Idioms", text: "Khi gặp lại một cụm quen thuộc, hãy kiểm tra xem nó có đang mang nghĩa khác không." },
  { category: "7. Phrasal Verbs & Idioms", text: "Hãy học những cụm bạn thực sự có khả năng gặp và sử dụng." },
  { category: "7. Phrasal Verbs & Idioms", text: "Một cụm được nhớ trong ngữ cảnh sẽ dễ sử dụng hơn một cụm học thuộc lòng." },
  { category: "8. Word Family – Họ từ", text: "Khi học một từ, hãy xem nó còn có những dạng liên quan nào." },
  { category: "8. Word Family – Họ từ", text: "Học các dạng từ cùng nhau sẽ giúp bạn dễ nhận ra chúng hơn." },
  { category: "8. Word Family – Họ từ", text: "Đừng chỉ ghi nghĩa, hãy xem từng dạng được dùng như thế nào." },
  { category: "8. Word Family – Họ từ", text: "Hãy đặt câu với những dạng khác nhau của cùng một từ." },
  { category: "8. Word Family – Họ từ", text: "Nếu biết một từ nhưng không nhận ra dạng khác, hãy học chúng cạnh nhau." },
  { category: "8. Word Family – Họ từ", text: "Chú ý rằng các dạng khác nhau có thể thay đổi cách dùng." },
  { category: "8. Word Family – Họ từ", text: "Đừng mặc định mọi dạng của một từ đều tồn tại." },
  { category: "8. Word Family – Họ từ", text: "Hãy ưu tiên những dạng thường xuyên xuất hiện." },
  { category: "8. Word Family – Họ từ", text: "Khi ôn từ, thử nhớ thêm những từ cùng họ." },
  { category: "8. Word Family – Họ từ", text: "Học theo nhóm sẽ giúp bạn mở rộng vốn từ nhanh hơn học từng từ riêng lẻ." },
  { category: "9. Reviewing – Khi 'nhìn quen nhưng không nhớ'", text: "Quen mắt không có nghĩa là bạn đã thực sự thuộc từ." },
  { category: "9. Reviewing – Khi 'nhìn quen nhưng không nhớ'", text: "Hãy thử nhớ nghĩa trước khi nhìn đáp án." },
  { category: "9. Reviewing – Khi 'nhìn quen nhưng không nhớ'", text: "Nếu chỉ nhìn đáp án mới nhớ ra, hãy đánh dấu từ đó để ôn lại." },
  { category: "9. Reviewing – Khi 'nhìn quen nhưng không nhớ'", text: "Thử tự đặt câu mà không nhìn ví dụ." },
  { category: "9. Reviewing – Khi 'nhìn quen nhưng không nhớ'", text: "Hãy thử giải thích từ bằng tiếng Anh mà không nhìn gợi ý." },
  { category: "9. Reviewing – Khi 'nhìn quen nhưng không nhớ'", text: "Đừng đánh dấu 'đã thuộc' chỉ vì bạn nhận ra từ khi nhìn thấy." },
  { category: "9. Reviewing – Khi 'nhìn quen nhưng không nhớ'", text: "Hãy kiểm tra xem bạn có thể tự nhớ từ trong một tình huống mới không." },
  { category: "9. Reviewing – Khi 'nhìn quen nhưng không nhớ'", text: "Nếu thường xuyên nhận ra nhưng không tự nhớ được, hãy dành thêm thời gian ôn từ đó." },
  { category: "9. Reviewing – Khi 'nhìn quen nhưng không nhớ'", text: "Thỉnh thoảng hãy kiểm tra những từ bạn tưởng mình đã thuộc." }
];